# Generated by Django 2.1.4 on 2018-12-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('vote_average', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='original_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='region',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='region',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='site',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='site_key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='tmdb_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailerapp.Film'),
        ),
        migrations.AddField(
            model_name='genre',
            name='films',
            field=models.ManyToManyField(to='trailerapp.Film'),
        ),
    ]
