# Generated by Django 2.1.4 on 2018-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0002_auto_20181216_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='tmdb_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
