# Generated by Django 2.1.4 on 2018-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0003_auto_20181217_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
