# Generated by Django 2.1.4 on 2018-12-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0004_auto_20181217_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='language',
            new_name='original_language',
        ),
    ]
