# Generated by Django 2.1.4 on 2018-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailerapp', '0007_film_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='trailerapp.Genre'),
        ),
    ]
